{{- with .Values.config }}{{- if not .existingConfigMap.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "config-map.name" $ }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
data:
  {{ include "config-map.key" $ }}:
    {{- .configYaml | nindent 4 }}
{{ end }}{{ end }}
