{{- with .Values.config }}{{- if not .existingConfigMap.enabled }}
{{- $validation := required "[VALIDATION] Missing required value(s): 'configYaml', '.configYaml.endpoints'" (and .configYaml .configYaml.endpoints) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "config-map.name" $ }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
data:
  {{ include "config-map.key" $ }}: |
    {{- toYaml .configYaml | nindent 4 }}
{{ end }}{{ end }}
