{{- with .Values.config }}{{- if not .existingConfigMap }}
{{- $validation := required "[VALIDATION] Missing required value(s): 'configYaml', '.configYaml.endpoints'" (and .configYaml .configYaml.endpoints) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "provider-config.name" $ }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .configYaml | nindent 4 }}
{{ end }}{{ end }}
