{{- with .Values.metrics.rules }}{{- if .enabled }}
---
apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: {{ include "common.fullname" $ }}-alerts
  namespace: {{ default ( include "common.namespace" $ ) .namespace }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .spec }}
  groups:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}{{- end }}