{{- with .Values.serviceAccount }}{{- if .enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ default ( include "common.fullname" $ ) .nameOverride }}
  namespace: {{ include "common.namespace" $ }}
  labels: {{- include "common.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .automountServiceAccountToken }}
automountServiceAccountToken: {{ . }}
{{- end }}
{{- with $.Values.provider.image.pullSecrets }}
imagePullSecrets:
{{- range . }}
- name: {{ .name }}
{{- end }}
{{- end }}
{{- end }}{{- end }}
