{{- with .Values.service }}{{- if .enabled }}
{{- $validation := required "[VALIDATION] Missing one or more required values for Service: 'type', 'port.name', 'port.number'" (and .type .port.name .port.number) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ default ( include "common.fullname" $ ) .nameOverride }}
  namespace: {{ include "common.namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .type }}
  ports:
    - name: {{ .port.name }}
      port: {{ .port.number }}
      targetPort: {{ .port.name }}
      protocol: TCP
    {{- with $.Values.metrics }}{{- if .enabled }}
    - name: {{ .port.name }}
      port: {{ .port.number }}
      protocol: TCP
      targetPort: {{ .port.name }}
    {{- end }}{{- end }}
  {{- if and .clusterIP (eq .type "ClusterIP") }}
  clusterIP: {{ .clusterIP }}
  {{- end }}
  {{- with .sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  {{- with .sessionAffinityConfig }}
  sessionAffinityConfig: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- if or (eq .type "LoadBalancer") (eq .type "NodePort") }}
  externalTrafficPolicy: {{ .externalTrafficPolicy }}
  {{- end }}
  {{- if and (eq .type "LoadBalancer") .loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ .loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .type "LoadBalancer") .loadBalancerIP }}
  loadBalancerIP: {{ .loadBalancerIP }}
  {{- end }}
  selector: {{- include "common.selectorLabels" $ | nindent 4 }}
{{- end }}{{- end }}
