{{- with .Values.provider.autoscaling.vpa }}{{- if .enabled }}
---
apiVersion: autoscaling/v2
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "common.fullname" $ }}
  namespace: {{ include "common.namespace" $ }}
  labels: {{- include "common.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations: {{- toYaml $ | nindent 4 }}
  {{- end }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledResources:
        {{- toYaml .controlledResources | nindent 8 }}
      maxAllowed: {{ .maxAllowed }}
      minAllowed: {{ .minAllowed }}
  targetRef:
    apiVersion: apps/v1
    kind: {{ if $.Values.persistence.enabled }}StatefulSet{{ else }}Deployment{{ end }}
    name: {{ include "common.fullname" $ }}
  {{- if .updatePolicy }}
  updatePolicy:
    updateMode: {{ .updatePolicy.updateMode }}
  {{- end }}
{{- end }}{{- end }}
